### ISSUE TITLE
Transfer project to team for better url

### ISSUE THREAD

**Issue by szkocot** [pl-ds-dict/pl-ds-dict.github.com#10]
If the project will be transferred to the newly created team, there will be possibility to create clean URL for the project, like pldsdict.github.io. It does not change, that all credits for the idea about this project belong to you @tpietruszka.

**Comment by tpietruszka** [comment]
Great idea! I somehow thought that teams were only available as a paid feature...

also I like the pl ds dict, much shorter, do you think its best as a single word, or perhaps with dashes?

**Comment by szkocot** [comment]
Or even better, we could make a team with the name corresponding to Data Science PL FB group - Data Science PL and place the dictionary under name.github.io/dictionary. I think we could ask Piotr M. (https://github.com/stared) for an opinion as he is one of the creators of this group.

Imho this needs more opinions and votes to make the right decision.

**Comment by tpietruszka** [comment]
Sounds good too, but then the address will be slightly weird again.
I kinda prefer the previous option.
Also, not sure if there is enough interest at this point to have any debate
@stared ?

**Comment by stared** [comment]
I am much for bottom-up activity. At that point, I am not interested in creating nor maintaining a Data Science PL GitHub group.

The address is the simplest part, and we can change it at any point, anyway.

**Comment by szkocot** [comment]
Okay, so "pl-ds-dict" sounds okay @tpietruszka?

**Comment by tpietruszka** [comment]
Sounds okay, and its done. 

It was a bit of a mess, because while Project Pages can be served from branches different than master, User/Organization Pages cannot. 

So unfortunately I had to rename branches, with `master` now called `source` and `gh-pages` now called... `master`. Unfortunately it breaks all repos checked out before this change. I don't think there was a way around that though.

Resolved by 3f5bb266bbd47f50882aaf2b3f0f984e424856d8 (and repo transfer)
